### ISSUE TITLE
Long lights stop

### ISSUE THREAD

**Issue by Tuchan** [mat1jaczyyy/lpp-performance-cfw#16]
Lets say there is a long light effect on launchpad (using lightweight obviosuly) Is there any method to stop all lights with a single button? (something like stop button in ableton + light stop in midifire implemented into custom firmware "menu" button)

**Comment by mat1jaczyyy** [comment]
How is this related to the firmware? It's not our problem if we just interpret what Ableton is sending and display it.

A light stop can be implemented manually into a M4L device which uses a [seq] (all MIDIext variants), but not tied up to Live's stop button because the API implementation for it is bad and broken. A manual stop could be added there, but this is not an issue for the custom firmware.
