### ISSUE TITLE
Multi reset issue

### ISSUE THREAD

**Issue by BattaNico** [mat1jaczyyy/lpp-performance-cfw#29]
Pressing the "setup" button on LP PRO doesn't reset the Multi device anymore

**Comment by TheLifeGamingYT** [comment]
I have this problem too

**Comment by mat1jaczyyy** [comment]
Is this in Apollo or Ableton, and what version? Are you using the latest outbreak devices?

**Comment by TheLifeGamingYT** [comment]
It's in Ableton and I'm using the latest outbreak

**Comment by BattaNico** [comment]
I'm using all the latest version of both outbreak and cfw

**Comment by mat1jaczyyy** [comment]
Just found some time to test. Testing with latest CFW, Multi Reset works as intended. Note that the reset trigger happens when you ENTER performance mode, so a transition from setup mode to performance mode should reset your multisamples. Live mode does NOT support this feature. If you're still sure that there's an issue, please re-open and provide a Live set / project file which can consistently reproduce the issue.
